### ISSUE TITLE
this package is no longer maintained and propably broken

### ISSUE THREAD

**Issue by Molnfront** [shreyas-jadhav/mui-audio-player#2]
Installing in react 17 app:

npm WARN deprecated prop-type@0.0.1: this package is no longer maintained and propably broken
npm ERR! code 127
npm ERR! path /Users/nisse/Documents/app/node_modules/mui-audio-player-plus
npm ERR! command failed

**Comment by shreyas-jadhav** [comment]
strange. it's working for me in react 17 app.

**Comment by shreyas-jadhav** [comment]
stale
